on:
  pull_request:
    branches:
      - main
      - rel-1877
      - sta-1877
  push:
    branches:
      - main
      - "rel-*"

  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    uses: gardenlinux/package-build/.github/workflows/build.yml@c571525680671caeac7a1471cd7f2ca812f96474 # main
    with:
      release: false
      # set publish release to true if we have no PR
      publish_release: ${{ github.event_name != 'pull_request' }}
