on:
  push:
    branches:
      - main
      - "rel-*"
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    uses: gardenlinux/package-build/.github/workflows/build.yml@main
    with:
      release: false
      # set publish release to true if we have no PR
      publish_release: ${{ github.event_name != 'pull_request' }}
